### ISSUE TITLE
How to sample from VLAE

### ISSUE THREAD

**Issue by gerwang** [yookoon/VLAE#3]
I want to ask a technical question related to the paper: Although the posterior distribution takes a form of full covariance gaussian, the prior distribution is still factorized gaussian. When we sample from a VAE we often sample from its **prior** distribution. When we sample from VLAE, should we sample from its prior (i.e. N(0,I))? Does VLAE take the advantage of full covariance distribution when sampling (Otherwise VLAE is just a technique that improves learning convergence)?

**Comment by yookoon** [comment]
You are right. VLAE's advantage comes from improved posterior inference and the generative part remains the same as VAEs. Therefore, if you want to sample from the generative distribution, you should sample from N(0, I).
